[amoji]
  [amojis.acid]
    words = ['acid']
    amoji = "âŠ‚(â—‰â€¿â—‰)ã¤"
  [amojis.afraid]
    words = ['afraid']
    amoji = "(ã†† _ ã††)"
  [amojis.angel]
    words = ['angel']
    amoji = "â˜œ(âŒ’â–½âŒ’)â˜"
  [amojis.angry]
    words = ['angry']
    amoji = "â€¢`_Â´â€¢"
  [amojis.arrowhead]
    words = ['arrowhead']
    amoji = "â¤œ(â±º Ê–Ì¯â±º)â¤"
  [amojis.apple]
    words = ['apple']
    amoji = "ï£¿"
  [amojis.ass]
    words = ['ass', 'butt']
    amoji = "(â€¿|â€¿)"
  [amojis.awkward]
    words = ['awkward']
    amoji = "â€¢Í¡Ë˜ã‡â€¢Í¡Ë˜"
  [amojis.bat]
    words = ['bat']
    amoji = "/|\\ ^._.^ /|\\"
  [amojis.bear]
    words = ['bear', 'koala']
    amoji = "Ê•Â·Í¡á´¥Â·Ê”ï»¿"
  [amojis.bearflip]
    words = ['bearflip']
    amoji = "Ê•ãƒâ€¢á´¥â€¢Ê”ãƒ ï¸µ â”»â”â”»"
  [amojis.bearhug]
    words = ['bearhug']
    amoji = "Ê•ã£â€¢á´¥â€¢Ê”ã£"
  [amojis.because]
    words = ['because', 'since']
    amoji = "âˆµ"
  [amojis.bigheart]
    words = ['bigheart']
    amoji = "â¤"
  [amojis.blackeye]
    words = ['blackeye']
    amoji = "0__#"
  [amojis.blubby]
    words = ['blubby']
    amoji = "(      0    _   0    )"
  [amojis.blush]
    words = ['blush']
    amoji = "(Ëµ Í¡Â° ÍœÊ– Í¡Â°Ëµ)"
  [amojis.bond]
    words = ['bond', '007']
    amoji = "â”Œ( ÍÂ° ÍœÊ–Í¡Â°)=Îµ/ÌµÍ‡Ì¿Ì¿/â€™Ì¿â€™Ì¿ Ì¿"
  [amojis.boobs]
    words = ['boobs']
    amoji = "( . Y . )"
  [amojis.bored]
    words = ['bored']
    amoji = "(-_-)"
  [amojis.bribe]
    words = ['bribe']
    amoji = "( â€¢Í¡Ë˜ _â€¢Í¡Ë˜)ãƒÃ°"
  [amojis.bubbles]
    words = ['bubbles']
    amoji = "( Ë˜ Â³Ë˜)ãƒÂ°ï¾ŸÂºâï½¡"
  [amojis.butterfly]
    words = ['butterfly']
    amoji = "Æ¸ÓœÆ·"
  [amojis.cat]
    words = ['cat']
    amoji = "(= Ğ¤ã‚§Ğ¤=)"
  [amojis.catlenny]
    words = ['catlenny']
    amoji = "( Í¡Â° á´¥ Í¡Â°)ï»¿"
  [amojis.checkmark]
    words = ['check']
    amoji = "âœ“"
  [amojis.chubby]
    words = ['chubby']
    amoji = "â•­(Ê˜Ì†~â—à±ªâ—Ÿ~Ê˜Ì†)â•®"
  [amojis.claro]
    words = ['claro']
    amoji = "(Í¡ Â° ÍœÊ– Í¡ Â°)"
  [amojis.clique]
    words = ['clique', 'gang', 'squad']
    amoji = "ãƒ½à¼¼ àºˆÙ„Íœàºˆà¼¼ â–€Ì¿Ì¿Ä¹Ì¯Ì¿Ì¿â–€Ì¿ Ì¿à¼½ÆŸÍ†Ù„ÍœÆŸÍ† à¼½ï¾‰"
  [amojis.cloud]
    words = ['cloud']
    amoji = "â˜"
  [amojis.club]
    words = ['club']
    amoji = "â™£"
  [amojis.coffee]
    words = ['coffee', 'cuppa']
    amoji = "c[_]"
  [amojis.command]
    words = ['cmd', 'command']
    amoji = "âŒ˜"
  [amojis.cool]
    words = ['cool', 'csi']
    amoji = "(â€¢_â€¢) ( â€¢_â€¢)>âŒâ– -â–  (âŒâ– _â– )"
  [amojis.copyright]
    words = ['copy','c']
    amoji = "Â©"
  [amojis.creep]
    words = ['creep']
    amoji = "Ô…(â‰–â€¿â‰–Ô…)"
  [amojis.creepcute]
    words = ['creepcute']
    amoji = "Æª(Ú“×²)â€Æªâ€‹â€‹"
  [amojis.crim3s]
    words = ['crim3s']
    amoji = "( âœœï¸µâœœ )"
  [amojis.cross]
    words = ['cross']
    amoji = "â€ "
  [amojis.cry]
    words = ['cry']
    amoji = "(â•¥ï¹â•¥)"
  [amojis.crywave]
    words = ['crywave']
    amoji = "( â•¥ï¹â•¥) ãƒã‚·"
  [amojis.cute]
    words = ['cute']
    amoji = "(ï½¡â—•â€¿â€¿â—•ï½¡)"
  [amojis.d1]
    words = ['d1']
    amoji = "âš€"
  [amojis.d2]
    words = ['d2']
    amoji = "âš"
  [amojis.d3]
    words = ['d3']
    amoji = "âš‚"
  [amojis.d4]
    words = ['d4']
    amoji = "âšƒ"
  [amojis.d5]
    words = ['d5']
    amoji = "âš„"
  [amojis.d6]
    words = ['d6']
    amoji = "âš…"
  [amojis.damnyou]
    words = ['damnyou']
    amoji = "(á•— Í Â° à¨Š Í Â° )á•—"
  [amojis.dance]
    words = ['dance']
    amoji = "á••(âŒâ– _â– )á•— â™ªâ™¬"
  [amojis.dead]
    words = ['dead']
    amoji = "xâ¸‘x"
  [amojis.dealwithit]
    words = ['dealwithit', 'dwi']
    amoji = "(âŒâ– _â– )"
  [amojis.delta]
    words = ['delta']
    amoji = "Î”"
  [amojis.depressed]
    words = ['depressed']
    amoji = "(ï¸¶ï¸¹ï¸¶)"
  [amojis.derp]
    words = ['derp']
    amoji = "â˜‰ â€¿ âš†"
  [amojis.diamond]
    words = ['diamond']
    amoji = "â™¦"
  [amojis.dog]
    words = ['dog']
    amoji = "(â—•á´¥â—•Ê‹)"
  [amojis.dollar]
    words = ['dollar']
    amoji = "$"
  [amojis.dong]
    words = ['dong']
    amoji = "(Ì¿â–€Ì¿â€‰Ì¿Ä¹Ì¯Ì¿Ì¿â–€Ì¿ Ì¿)Ì„",
  [amojis.donger]
    words = ['donger']
    amoji = "ãƒ½à¼¼àºˆÙ„Íœàºˆà¼½ï¾‰",
  [amojis.dontcare]
    words = ['dontcare']
    amoji = "â•­âˆ©â•®ï¼ˆï¸¶ï¸¿ï¸¶ï¼‰â•­âˆ©â•®"
  [amojis.donotwant]
    words = ['do not want', 'dontwant']
    amoji = "ãƒ½(ï½€Ğ”Â´)ï¾‰"
  [amojis.dope]
    words = ['dope']
    amoji = "<(^_^)>"
  [amojis.doublequotesleft]
    words = ['<<']
    amoji = "Â«"
  [amojis.doublequotesright]
    words = ['>>']
    amoji = "Â»"
  [amojis.doubleflat]
    words = ['doubleflat']
    amoji = "ğ„«"
  [amojis.doublesharp]
    words = ['doublesharp']
    amoji = "ğ„ª"
  [amojis.doubletableflip]
    words = ['doubletableflip']
    amoji = "â”»â”â”» ï¸µãƒ½(`Ğ”Â´)ï¾‰ï¸µ â”»â”â”»"
  [amojis.down]
    words = ['down']
    amoji = "â†“"
  [amojis.duckface]
    words = ['duckface']
    amoji = "(ãƒ»3ãƒ»)"
  [amojis.duel]
    words = ['duel']
    amoji = "á••(â•­à²°â•­ ÍŸÊ–â•®â€¢Ì)âŠƒÂ¤=(â€”â€”â€”â€”-"
  [amojis.duh]
    words = ['duh']
    amoji = "(â‰§ï¸¿â‰¦)"
  [amojis.dunnolol]
    words = ['dunno']
    amoji = "Â¯\\(Â°_o)/Â¯"
  [amojis.ebola]
    words = ['ebola']
    amoji = "á´‡Ê™á´ÊŸá´€"
  [amojis.ellipsis]
    words = ['ellipsis', '...']
    amoji = "â€¦"
  [amojis.emdash]
    words = ['emdash', '--']
    amoji = "â€“"
  [amojis.emptystar]
    words = ['emptystar']
    amoji = "â˜†"
  [amojis.emptytriangle]
    words = ['emptytriangle', 't2']
    amoji = "â–³"
  [amojis.endure]
    words = ['endure']
    amoji = "(Ò‚â—¡_â—¡) á•¤"
  [amojis.envelope]
    words = ['envelope', 'letter']
    amoji = "âœ‰ï¸"
  [amojis.epsilon]
    words = ['epsilon']
    amoji = "É›"
  [amojis.euro]
    words = ['euro']
    amoji = "â‚¬"
  [amojis.evil]
    words = ['evil']
    amoji = "Ïˆ(ï½€âˆ‡Â´)Ïˆ"
  [amojis.evillenny]
    words = ['evillenny']
    amoji = "(Í â‰– ÍœÊ–Í â‰–)"
  [amojis.execution]
    words = ['execution']
    amoji = "(âŒâ– _â– )ï¸»â•¦â•¤â”€   (â•¥ï¹â•¥)"
  [amojis.facebook]
    words = ['facebook']
    amoji = "(â•¯Â°â–¡Â°)â•¯ï¸µ ÊooqÇÉ”ÉÉŸ"
  [amojis.facepalm]
    words = ['facepalm']
    amoji = "(ï¼â€¸áƒš)"
  [amojis.fart]
    words = ['fart']
    amoji = "(Ë†âº«Ë†à¹‘)<3"
  [amojis.fight]
    words = ['fight']
    amoji = "(à¸‡ â€¢Ì€_â€¢Ì)à¸‡"
  [amojis.finn]
    words = ['finn']
    amoji = "| (â€¢ â—¡â€¢)|"
  [amojis.fish]
    words = ['fish']
    amoji = "<"(((<3"
  [amojis.five]
    words = ['5', 'five']
    amoji = "åŒ"
  [amojis.fiveeights]
    words = ['5/8']
    amoji = "â…"
  [amojis.flat]
    words = ['flat', 'bemolle']
    amoji = "â™­"
  [amojis.flexing]
    words = ['flexing']
    amoji = "á•™(`â–½Â´)á•—"
  [amojis.flipped]
    words = ['flipped', 'heavytable']
    amoji = "â”¬â”€â”¬ï»¿ ï¸µ /(.â–¡. \\ï¼‰"
  [amojis.flower]
    words = ['flower', 'flor']
    amoji = "(âœ¿â— â€¿â— )"
  [amojis.flower2]
    words = ['f']
    amoji = "âœ¿"
  [amojis.fly]
    words = ['fly']
    amoji = "â”€=â‰¡Î£((( ã¤â—•Ù„Íœâ—•)ã¤"
  [amojis.friendflip]
    words = ['friendflip']
    amoji = "(â•¯Â°â–¡Â°)â•¯ï¸µ â”»â”â”» ï¸µ â•¯(Â°â–¡Â° â•¯)"
  [amojis.frown]
    words = ['frown']
    amoji = "(áƒ¦Ë˜âŒ£Ë˜áƒ¦)"
  [amojis.fuckoff]
    words = ['fuckoff', 'gtfo']
    amoji = "à­§à¼¼à² ç›Šà² â•­âˆ©â•®à¼½"
  [amojis.fuckyou]
    words = ['fuckyou', 'fu']
    amoji = "â”ŒĞŸâ”(à² _à² )"
  [amojis.gentleman]
    words = ['gentleman', 'sir', 'monocle']
    amoji = "à² _à²°à³ƒ"
  [amojis.ghast]
    words = ['ghast']
    amoji = "= _ ="
  [amojis.ghost]
    words = ['ghost']
    amoji = "à¼¼ ã¤ â_â à¼½ã¤"
  [amojis.gift]
    words = ['gift', 'present']
    amoji = "(Â´ãƒ»Ï‰ãƒ»)ã£ç”±",
  [amojis.gimme]
    words = ['gimme']
    amoji = "à¼¼ ã¤ â—•_â—• à¼½ã¤"
  [amojis.glitterbomb]
    words = ['glitter']
    amoji = "(*ãƒ»â€¿ãƒ»)ãƒâŒ’*:ï½¥ï¾Ÿâœ§"
  [amojis.glasses]
    words = ['glasses']
    amoji = "(âŒ Í¡â–  ÍœÊ– Í¡â– )"
  [amojis.glassesoff]
    words = ['glassesoff']
    amoji = "( Í¡Â° ÍœÊ– Í¡Â°)ï¾‰âŒâ– -â– "
  [amojis.glitterderp]
    words = ['glitterderp']
    amoji = "(ï¾‰â˜‰ãƒ®âš†)ï¾‰ âŒ’*:ï½¥ï¾Ÿâœ§"
  [amojis.gloomy]
    words = ['gloomy']
    amoji = "(_ã‚œ_ã‚œ_)"
  [amojis.goatse]
    words = ['goatse']
    amoji = "(Ğ·à¹Îµ)"
  [amojis.gotit]
    words = ['gotit']
    amoji = "(â˜ï¾Ÿâˆ€ï¾Ÿ)â˜"
  [amojis.greet]
    words = ['greet', 'greetings']
    amoji = "( Â´â—” Ï‰â—”`) ãƒã‚·"
  [amojis.gun]
    words = ['gun', 'mg']
    amoji = "ï¸»â•¦â•¤â”€"
  [amojis.hadouken]
    words = ['hadouken']
    amoji = "à¼¼ã¤à² ç›Šà² à¼½ã¤ â”€=â‰¡Î£O))"
  [amojis.hammerandsickle]
    words = ['hammerandsickle', 'hs']
    amoji = "â˜­"
  [amojis.handleft]
    words = ['handleft', 'hl']
    amoji = "â˜œ"
  [amojis.handright]
    words = ['handright', 'hr']
    amoji = "â˜"
  [amojis.haha]
    words = ['haha']
    amoji = "Ù©(^â€¿^)Û¶"
  [amojis.happy]
    words = ['happy']
    amoji = "Ù©( à¹‘â•¹ ê‡´â•¹)Û¶"
  [amojis.happygarry]
    words = ['happygarry']
    amoji = "á••( á› )á•—"
  [amojis.heart]
    words = ['h', 'heart']
    amoji = "â™¥"
  [amojis.hello]
    words = ['hello', 'ohai', 'bye']
    amoji = "(Ê˜â€¿Ê˜)â•¯"
  [amojis.highfive]
    words = ['highfive']
    amoji = "._.)/\\(._."
  [amojis.hitting]
    words = ['hitting']
    amoji = "( ï½€çš¿Â´)ï½¡ï¾/"
  [amojis.hugs]
    words = ['hug', 'hugs']
    amoji = "(ã¥ï½¡â—•â€¿â€¿â—•ï½¡)ã¥"
  [amojis.iknowright]
    words = ['iknowright', 'ikr']
    amoji = "â”ï½œï½¥à¸´Ï‰ï½¥à¸´#ï½œâ”Œ"
  [amojis.illuminati]
    words = ['illuminati']
    amoji = "à­§(â–²á´—â–²)ãƒ"
  [amojis.infinity]
    words = ['infinity', 'inf']
    amoji = "âˆ"
  [amojis.inlove]
    words = ['inlove']
    amoji = "(ã£Â´Ï‰`c)â™¡"
  [amojis.integral]
    words = ['int']
    amoji = "âˆ«"
  [amojis.internet]
    words = ['internet']
    amoji = "à¬˜(à©­*ËŠáµ•Ë‹)à©­*â€ŠÌ€Ë‹ ÉªÉ´á´›á´‡Ê€É´á´‡á´›"
  [amojis.interrobang]
    words = ['interrobang']
    amoji = "â€½"
  [amojis.jake]
    words = ['jake']
    amoji = "(âá´¥âÊ‹)"
  [amojis.kawaii]
    words = ['kawaii']
    amoji = "â‰§â—¡â‰¦"
  [amojis.keen]
    words = ['keen']
    amoji = "â”¬â”´â”¬â”´â”¤ÆŸÍ†Ù„ÍœÆŸÍ† à¼½ï¾‰"
  [amojis.kiahh]
    words = ['kiahh']
    amoji = "~\\(â‰§â–½â‰¦)/~"
  [amojis.kiss]
    words = ['kiss']
    amoji = "(ã¥ ï¿£ Â³ï¿£)ã¥"
  [amojis.kyubey]
    words = ['kyubey']
    amoji = "ï¼äººâ—• â€¿â€¿ â—•äººï¼¼"
  [amojis.lambda]
    words = ['lambda']
    amoji = "Î»"
  [amojis.lazy]
    words = ['lazy']
    amoji = "_(:3ã€âˆ )_"
  [amojis.left]
    words = ['left', '<-']
    amoji = "â†"
  [amojis.lenny]
    words = ['lenny']
    amoji = "( Í¡Â° ÍœÊ– Í¡Â°)"
  [amojis.lennybill]
    words = ['lennybill']
    amoji = "[Ì²Ì…$Ì²Ì…(Ì²Ì… Í¡Â° ÍœÊ– Í¡Â°Ì²Ì…)Ì²Ì…$Ì²Ì…]"
  [amojis.lennyfight]
    words = ['lennyfight']
    amoji = "(à¸‡ Í Â° ÍŸÊ– Í¡Â°)à¸‡"
  [amojis.lennyflip]
    words = ['lennyflip']
    amoji = "(ãƒ Í¡Â° ÍœÊ– Í¡Â°ãƒ)   ï¸µ ( Íœã€‚ Í¡Ê– Íœã€‚)"
  [amojis.lennygang]
    words = ['lennygang']
    amoji = "( Í¡Â°( Í¡Â° ÍœÊ–( Í¡Â° ÍœÊ– Í¡Â°)Ê– Í¡Â°) Í¡Â°)"
  [amojis.lennyshrug]
    words = ['lennyshrug']
    amoji = "Â¯\\_( Í¡Â° ÍœÊ– Í¡Â°)_/Â¯"
  [amojis.lennysir]
    words = ['lennysir']
    amoji = "( à²  ÍœÊ– à²°à³ƒ)"
  [amojis.lennystalker]
    words = ['lennystalker']
    amoji = "â”¬â”´â”¬â”´â”¤( Í¡Â° ÍœÊ–â”œâ”¬â”´â”¬â”´"
  [amojis.lennystrong]
    words = ['lennystrong']
    amoji = "á•¦( Í¡Â° ÍœÊ– Í¡Â°)á•¤"
  [amojis.lennywizard]
    words = ['lennywizard']
    amoji = "â•°( Í¡Â° ÍœÊ– Í¡Â° )ã¤â”€â”€â˜†*:ãƒ»ï¾Ÿ"
  [amojis.lol]
    words = ['lol']
    amoji = "L(Â° O Â°L)"
  [amojis.look]
    words = ['look']
    amoji = "(à²¡_à²¡)â˜"
  [amojis.love]
    words = ['love']
    amoji = "â™¥â€¿â™¥"
  [amojis.lovebear]
    words = ['lovebear']
    amoji = "Ê•â™¥á´¥â™¥Ê”"
  [amojis.lumpy]
    words = ['lumpy']
    amoji = "ê’° ê’¡âŒ“ê’¡ê’±"
  [amojis.luv]
    words = ['luv']
    amoji = "-`áƒ¦Â´-"
  [amojis.magic]
    words = ['magic']
    amoji = "ãƒ½(ï½€Ğ”Â´)âŠƒâ”â˜†ï¾Ÿ. * ï½¥ ï½¡ï¾Ÿ,"
  [amojis.magicflip]
    words = ['magicflip']
    amoji = "(/Â¯â—¡ â€¿ â—¡)/Â¯ ~ â”»â”â”»"
  [amojis.meep]
    words = ['meep']
    amoji = "\\(Â°^Â°)/"
  [amojis.meh]
    words = ['meh']
    amoji = "à² _à² "
  [amojis.mistyeyes]
    words = ['mistyeyes']
    amoji = "à²¡_à²¡"
  [amojis.monster]
    words = ['monster']
    amoji = "à¼¼ à¼àº¶ à·´ à¼àº¶à¼½"
  [amojis.natural]
    words = ['natural']
    amoji = "â™®"
  [amojis.needle]
    words = ['needle', 'inject']
    amoji = "â”Œ(â—‰ ÍœÊ–â—‰)ã¤â”£â–‡â–‡â–‡â•â”€â”€"
  [amojis.nice]
    words = ['nice']
    amoji = "( Í¡Â° Íœ Â°)"
  [amojis.no]
    words = ['no']
    amoji = "â†’_â†"
  [amojis.noclue]
    words = ['noclue']
    amoji = "ï¼äººâ—• __ â—•äººï¼¼"
  [amojis.nom]
    words = ['nom', 'yummy', 'delicious']
    amoji = "(ã£Ë†Ú¡Ë†Ï‚)"
  [amojis.note]
    words = ['note', 'sing']
    amoji = "â™«"
  [amojis.nuclear]
    words = ['nuclear', 'radioactive', 'nukular']
    amoji = "â˜¢"
  [amojis.nyan]
    words = ['nyan']
    amoji = "~=[,,_,,]:3"
  [amojis.nyeh]
    words = ['nyeh']
    amoji = "@^@"
  [amojis.ohshit]
    words = ['ohshit']
    amoji = "( Âºï¹ƒÂº )"
  [amojis.omg]
    words = ['omg']
    amoji = "â—•_â—•"
  [amojis.oneeighth]
    words = ['1/8']
    amoji = "â…›"
  [amojis.onefourth]
    words = ['1/4']
    amoji = "Â¼"
  [amojis.onehalf]
    words = ['1/2']
    amoji = "Â½"
  [amojis.onethird]
    words = ['1/3']
    amoji = "â…“"
  [amojis.option]
    words = ['opt', 'option']
    amoji = "âŒ¥"
  [amojis.ohreally]
    words = ['orly']
    amoji = "(ëˆˆ_ëˆˆ)"
  [amojis.ohyou]
    words = ['ohyou', 'ou']
    amoji = "(â—à°¥à±ªà°¥)á´–"
  [amojis.peace]
    words = ['peace', 'victory']
    amoji = "âœŒ(-â€¿-)âœŒ"
  [amojis.pear]
    words = ['pear']
    amoji = "(__>-"
  [amojis.pi]
    words = ['pi']
    amoji = "Ï€"
  [amojis.pingpong]
    words = ['pingpong']
    amoji = "( â€¢_â€¢)O*Â¯`Â·.Â¸.Â·Â´Â¯`Â°Q(â€¢_â€¢ )"
  [amojis.plain]
    words = ['plain']
    amoji = "._."
  [amojis.pleased]
    words = ['pleased']
    amoji = "(Ë¶â€¾á·„ â»Ì« â€¾á·…Ëµ)"
  [amojis.point]
    words = ['point']
    amoji = "(â˜ï¾Ÿãƒ®ï¾Ÿ)â˜"
  [amojis.pooh]
    words = ['pooh']
    amoji = "Ê• â€¢ÌØˆâ€¢Ì€)"
  [amojis.porcupine]
    words = ['porcupine']
    amoji = "(â€¢á´¥â€¢ )Ì`Ì\'Ì`Ì\'Ìâ»"
  [amojis.pound]
    words = ['pound']
    amoji = "Â£"
  [amojis.praise]
    words = ['praise']
    amoji = "(â˜ Õà¨Š Õ)â˜"
  [amojis.punch]
    words = ['punch']
    amoji = "O=(\'-\'Q)"
  [amojis.rage]
    words = ['rage', 'mad']
    amoji = "t(à² ç›Šà² t)"
  [amojis.rageflip]
    words = ['rageflip']
    amoji = "(ãƒà² ç›Šà² )ãƒå½¡â”»â”â”»"
  [amojis.rainbowcat]
    words = ['rainbowcat']
    amoji = "(=^ï½¥ï½ªï½¥^=))ï¾‰å½¡â˜†"
  [amojis.really]
    words = ['really']
    amoji = "Ã²_Ã´"
  [amojis.registered]
    words = ['r']
    amoji = "Â®"
  [amojis.right]
    words = ['right', '->']
    amoji = "â†’"
  [amojis.riot]
    words = ['riot']
    amoji = "à­§à¼¼à² ç›Šà² à¼½à­¨"
  [amojis.rolleyes]
    words = ['rolleyes']
    amoji = "(â—”_â—”)"
  [amojis.rose ]
    words = ['rose']
    amoji = "âœ¿Ú¿Ú°Û£â€”"
  [amojis.run]
    words = ['run']
    amoji = "(â•¯Â°â–¡Â°)â•¯"
  [amojis.sad]
    words = ['sad']
    amoji = "Îµ(Â´ï­ï¸µï­`)Ğ·"
  [amojis.saddonger]
    words = ['saddonger']
    amoji = "ãƒ½à¼¼àºˆÊ–Ì¯àºˆà¼½ï¾‰"
  [amojis.sadlenny]
    words = ['sadlenny']
    amoji = "( Í¡Â° Ê–Ì¯ Í¡Â°)"
  [amojis.seveneigths]
    words = ['7/8']
    amoji = "â…"
  [amojis.sharp]
    words = ['sharp', 'diesis']
    amoji = "â™¯"
  [amojis.shout]
    words = ['shout']
    amoji = "â•š(â€¢âŒ‚â€¢)â•"
  [amojis.shrug]
    words = ['shrug']
    amoji = "Â¯\\_(ãƒ„)_/Â¯"
  [amojis.shy]
    words = ['shy']
    amoji = "=^_^="
  [amojis.sigma]
    words = ['sigma', 'sum']
    amoji = "Î£"
  [amojis.skull]
    words = ['skull']
    amoji = "â˜ "
  [amojis.smile]
    words = ['smile']
    amoji = "ãƒ„"
  [amojis.smiley]
    words = ['smiley']
    amoji = "â˜ºï¸"
  [amojis.smirk]
    words = ['smirk']
    amoji = "Â¬â€¿Â¬"
  [amojis.snowman]
    words = ['snowman']
    amoji = "â˜ƒ"
  [amojis.sob]
    words = ['sob']
    amoji = "(;Â´à¼àº¶Ğ”à¼àº¶`)"
  [amojis.spade]
    words = ['spade']
    amoji = "â™ "
  [amojis.squareroot]
    words = ['sqrt']
    amoji = "âˆš"
  [amojis.squid]
    words = ['squid']
    amoji = "<ã‚³:å½¡"
  [amojis.star]
    words = ['star']
    amoji = "â˜…"
  [amojis.strong]
    words = ['strong']
    amoji = "á•™(â‡€â€¸â†¼â€¶)á•—"
  [amojis.suicide]
    words = ['suicide']
    amoji = "Îµ/ÌµÍ‡Ì¿Ì¿/â€™Ì¿â€™Ì¿ Ì¿(â—¡ï¸µâ—¡)"
  [amojis.sum]
    words = ['sum']
    amoji = "âˆ‘"
  [amojis.sun]
    words = ['sun']
    amoji = "â˜€"
  [amojis.surprised]
    words = ['surprised']
    amoji = "(à¹‘â€¢Ì ãƒ® â€¢Ì€à¹‘)"
  [amojis.surrender]
    words = ['surrender']
    amoji = "\\_(-_-)_/",
  [amojis.stalker]
    words = ['stalker']
    amoji = "â”¬â”´â”¬â”´â”¤(ï½¥_â”œâ”¬â”´â”¬â”´"
  [amojis.swag]
    words = ['swag']
    amoji = "(Ì¿â–€Ì¿â€¿â€‰Ì¿â–€Ì¿ Ì¿)"
  [amojis.sword]
    words = ['sword']
    amoji = "o()xxxx[{::::::::::::::::::>"
  [amojis.tabledown]
    words = ['tabledown']
    amoji = "â”¬â”€â”¬ï»¿ ãƒ( ã‚œ-ã‚œãƒ)"
  [amojis.tableflip]
    words = ['tableflip']
    amoji = "(ãƒ ã‚œĞ”ã‚œ)ãƒ ï¸µ â”»â”â”»"
  [amojis.tau]
    words = ['tau']
    amoji = "Ï„"
  [amojis.tears]
    words = ['tears']
    amoji = "(à²¥ï¹à²¥)"
  [amojis.terrorist]
    words = ['terrorist']
    amoji = "à­§à¼¼à² ç›Šà² à¼½ï¸»â•¦â•¤â”€"
  [amojis.thanks]
    words = ['thanks', 'thankyou', 'ty']
    amoji = "\\(^-^)/"
  [amojis.therefore]
    words = ['therefore', 'so']
    amoji = "â¸«"
  [amojis.threeeights]
    words = ['3/8']
    amoji = "â…œ"
  [amojis.tiefighter]
    words = ['tiefighter']
    amoji = "|=-(Â¤)-=|"
  [amojis.tired]
    words = ['tired']
    amoji = "(=____=)"
  [amojis.toldyouso]
    words = ['toldyouso', 'toldyou']
    amoji = "â˜œ(ê’¡âŒ“ê’¡)"
  [amojis.toogood]
    words = ['toogood']
    amoji = "á•¦(Ã²á´¥Ã³)á•¥"
  [amojis.trademark]
    words = ['tm']
    amoji = "â„¢"
  [amojis.triangle]
    words = ['triangle', 't']
    amoji = "â–²"
  [amojis.twothirds]
    words = ['2/3']
    amoji = "â…”"
  [amojis.unflip]
    words = ['unflip']
    amoji = "â”¬â”€â”€â”¬ ãƒ(Ã²_Ã³ãƒ)"
  [amojis.up]
    words = ['up']
    amoji = "â†‘"
  [amojis.victory]
    words = ['victory']
    amoji = "(à¹‘â€¢Ì€ã…‚â€¢Ì)à¸‡âœ§"
  [amojis.wat]
    words = ['wat']
    amoji = "(Ã’Ğ”Ã“×±)"
  [amojis.wave]
    words = ['wave']
    amoji = "( * ^ *) ãƒã‚·"
  [amojis.whaa]
    words = ['whaa']
    amoji = "Ã–"
  [amojis.whistle]
    words = ['whistle']
    amoji = "(ã£^Ğ·^)â™ªâ™¬"
  [amojis.whoa]
    words = ['whoa']
    amoji = "(Â°oâ€¢)"
  [amojis.why]
    words = ['why']
    amoji = "áƒš(`â—‰â—à±ªâ—Ÿâ—‰â€µáƒš)"
  [amojis.woo]
    words = ['woo']
    amoji = "ï¼¼(ï¼¾Oï¼¾)ï¼"
  [amojis.wtf]
    words = ['wtf']
    amoji = "(âŠ™ï¼¿âŠ™\')"
  [amojis.wut]
    words = ['wut']
    amoji = "âŠ™Ï‰âŠ™"
  [amojis.yay]
    words = ['yay']
    amoji = "\\( ï¾Ÿãƒ®ï¾Ÿ)/"
  [amojis.yeah]
    words = ['yeah', 'yes']
    amoji = "(â€¢Ì€á´—â€¢Ì)Ùˆ Ì‘Ì‘"
  [amojis.yen]
    words = ['yen']
    amoji = "Â¥"
  [amojis.yinyang]
    words = ['yinyang', 'yy']
    amoji = "â˜¯"
  [amojis.yolo]
    words = ['yolo']
    amoji = "Yáµ’áµ˜ Oá¶°Ë¡Ê¸ Lá¶¤áµ›áµ‰ Oá¶°á¶œáµ‰"
  [amojis.youkids]
    words = ['youkids', 'ukids']
    amoji = "áƒšà¼¼>â•­ ÍŸÊ–â•®<à¼½áƒš"
  [amojis.yuno]
    words = ['y u no', 'yuno']
    amoji = "(å±®ï¾ŸĞ”ï¾Ÿ)å±® Y U NO"
  [amojis.zen]
    words = ['zen', 'meditation', 'omm']
    amoji = "âŠ¹â•°(âŒ£ÊŸâŒ£)â•¯âŠ¹"
  [amojis.zoidberg]
    words = ['zoidberg']
    amoji = "(V) (Â°,,,,Â°) (V)"
  [amojis.zombie]
    words = ['zombie']
    amoji = "[Â¬Âº-Â°]Â¬"
