[amoji]
  [amoji.acid]
    words = ['acid']
    amoji = 'âŠ‚(â—‰â€¿â—‰)ã¤'
  [amoji.afraid]
    words = ['afraid']
    amoji = '(ã†† _ ã††)'
  [amoji.angel]
    words = ['angel']
    amoji = 'â˜œ(âŒ’â–½âŒ’)â˜'
  [amoji.angry]
    words = ['angry']
    amoji = 'â€¢`_Â´â€¢'
  [amoji.arrowhead]
    words = ['arrowhead']
    amoji = 'â¤œ(â±º Ê–Ì¯â±º)â¤'
  [amoji.apple]
    words = ['apple']
    amoji = 'ï£¿'
  [amoji.ass]
    words = ['ass', 'butt']
    amoji = '(â€¿|â€¿)'
  [amoji.awkward]
    words = ['awkward']
    amoji = 'â€¢Í¡Ë˜ã‡â€¢Í¡Ë˜'
  [amoji.bat]
    words = ['bat']
    amoji = '/|\\ ^._.^ /|\\'
  [amoji.bear]
    words = ['bear', 'koala']
    amoji = 'Ê•Â·Í¡á´¥Â·Ê”ï»¿'
  [amoji.bearflip]
    words = ['bearflip']
    amoji = 'Ê•ãƒâ€¢á´¥â€¢Ê”ãƒ ï¸µ â”»â”â”»'
  [amoji.bearhug]
    words = ['bearhug']
    amoji = 'Ê•ã£â€¢á´¥â€¢Ê”ã£'
  [amoji.because]
    words = ['because', 'since']
    amoji = 'âˆµ'
  [amoji.bigheart]
    words = ['bigheart']
    amoji = 'â¤'
  [amoji.blackeye]
    words = ['blackeye']
    amoji = '0__#'
  [amoji.blubby]
    words = ['blubby']
    amoji = '(      0    _   0    )'
  [amoji.blush]
    words = ['blush']
    amoji = '(Ëµ Í¡Â° ÍœÊ– Í¡Â°Ëµ)'
  [amoji.bond]
    words = ['bond', '007']
    amoji = 'â”Œ( ÍÂ° ÍœÊ–Í¡Â°)=Îµ/ÌµÍ‡Ì¿Ì¿/â€™Ì¿â€™Ì¿ Ì¿'
  [amoji.boobs]
    words = ['boobs']
    amoji = '( . Y . )'
  [amoji.bored]
    words = ['bored']
    amoji = '(-_-)'
  [amoji.bribe]
    words = ['bribe']
    amoji = '( â€¢Í¡Ë˜ _â€¢Í¡Ë˜)ãƒÃ°'
  [amoji.bubbles]
    words = ['bubbles']
    amoji = '( Ë˜ Â³Ë˜)ãƒÂ°ï¾ŸÂºâï½¡'
  [amoji.butterfly]
    words = ['butterfly']
    amoji = 'Æ¸ÓœÆ·'
  [amoji.cat]
    words = ['cat']
    amoji = '(= Ğ¤ã‚§Ğ¤=)'
  [amoji.catlenny]
    words = ['catlenny']
    amoji = '( Í¡Â° á´¥ Í¡Â°)ï»¿'
  [amoji.checkmark]
    words = ['check']
    amoji = 'âœ“'
  [amoji.chubby]
    words = ['chubby']
    amoji = 'â•­(Ê˜Ì†~â—à±ªâ—Ÿ~Ê˜Ì†)â•®'
  [amoji.claro]
    words = ['claro']
    amoji = '(Í¡ Â° ÍœÊ– Í¡ Â°)'
  [amoji.clique]
    words = ['clique', 'gang', 'squad']
    amoji = 'ãƒ½à¼¼ àºˆÙ„Íœàºˆà¼¼ â–€Ì¿Ì¿Ä¹Ì¯Ì¿Ì¿â–€Ì¿ Ì¿à¼½ÆŸÍ†Ù„ÍœÆŸÍ† à¼½ï¾‰'
  [amoji.cloud]
    words = ['cloud']
    amoji = 'â˜'
  [amoji.club]
    words = ['club']
    amoji = 'â™£'
  [amoji.coffee]
    words = ['coffee', 'cuppa']
    amoji = 'c[_]'
  [amoji.command]
    words = ['cmd', 'command']
    amoji = 'âŒ˜'
  [amoji.cool]
    words = ['cool', 'csi']
    amoji = '(â€¢_â€¢) ( â€¢_â€¢)>âŒâ– -â–  (âŒâ– _â– )'
  [amoji.copyright]
    words = ['copy','c']
    amoji = 'Â©'
  [amoji.creep]
    words = ['creep']
    amoji = 'Ô…(â‰–â€¿â‰–Ô…)'
  [amoji.creepcute]
    words = ['creepcute']
    amoji = 'Æª(Ú“×²)â€Æªâ€‹â€‹'
  [amoji.crim3s]
    words = ['crim3s']
    amoji = '( âœœï¸µâœœ )'
  [amoji.cross]
    words = ['cross']
    amoji = 'â€ '
  [amoji.cry]
    words = ['cry']
    amoji = '(â•¥ï¹â•¥)'
  [amoji.crywave]
    words = ['crywave']
    amoji = '( â•¥ï¹â•¥) ãƒã‚·'
  [amoji.cute]
    words = ['cute']
    amoji = '(ï½¡â—•â€¿â€¿â—•ï½¡)'
  [amoji.d1]
    words = ['d1']
    amoji = 'âš€'
  [amoji.d2]
    words = ['d2']
    amoji = 'âš'
  [amoji.d3]
    words = ['d3']
    amoji = 'âš‚'
  [amoji.d4]
    words = ['d4']
    amoji = 'âšƒ'
  [amoji.d5]
    words = ['d5']
    amoji = 'âš„'
  [amoji.d6]
    words = ['d6']
    amoji = 'âš…'
  [amoji.damnyou]
    words = ['damnyou']
    amoji = '(á•— Í Â° à¨Š Í Â° )á•—'
  [amoji.dance]
    words = ['dance']
    amoji = 'á••(âŒâ– _â– )á•— â™ªâ™¬'
  [amoji.dead]
    words = ['dead']
    amoji = 'xâ¸‘x'
  [amoji.dealwithit]
    words = ['dealwithit', 'dwi']
    amoji = '(âŒâ– _â– )'
  [amoji.delta]
    words = ['delta']
    amoji = 'Î”'
  [amoji.depressed]
    words = ['depressed']
    amoji = '(ï¸¶ï¸¹ï¸¶)'
  [amoji.derp]
    words = ['derp']
    amoji = 'â˜‰ â€¿ âš†'
  [amoji.diamond]
    words = ['diamond']
    amoji = 'â™¦'
  [amoji.dog]
    words = ['dog']
    amoji = '(â—•á´¥â—•Ê‹)'
  [amoji.dollar]
    words = ['dollar']
    amoji = '$'
  [amoji.dong]
    words = ['dong']
    amoji = '(Ì¿â–€Ì¿â€‰Ì¿Ä¹Ì¯Ì¿Ì¿â–€Ì¿ Ì¿)Ì„'
  [amoji.donger]
    words = ['donger']
    amoji = 'ãƒ½à¼¼àºˆÙ„Íœàºˆà¼½ï¾‰'
  [amoji.dontcare]
    words = ['dontcare']
    amoji = 'â•­âˆ©â•®ï¼ˆï¸¶ï¸¿ï¸¶ï¼‰â•­âˆ©â•®'
  [amoji.donotwant]
    words = ['do not want', 'dontwant']
    amoji = 'ãƒ½(ï½€Ğ”Â´)ï¾‰'
  [amoji.dope]
    words = ['dope']
    amoji = '<(^_^)>'
  [amoji.doublequotesleft]
    words = ['<<']
    amoji = 'Â«'
  [amoji.doublequotesright]
    words = ['>>']
    amoji = 'Â»'
  [amoji.doubleflat]
    words = ['doubleflat']
    amoji = 'ğ„«'
  [amoji.doublesharp]
    words = ['doublesharp']
    amoji = 'ğ„ª'
  [amoji.doubletableflip]
    words = ['doubletableflip']
    amoji = 'â”»â”â”» ï¸µãƒ½(`Ğ”Â´)ï¾‰ï¸µ â”»â”â”»'
  [amoji.down]
    words = ['down']
    amoji = 'â†“'
  [amoji.duckface]
    words = ['duckface']
    amoji = '(ãƒ»3ãƒ»)'
  [amoji.duel]
    words = ['duel']
    amoji = 'á••(â•­à²°â•­ ÍŸÊ–â•®â€¢Ì)âŠƒÂ¤=(â€”â€”â€”â€”-'
  [amoji.duh]
    words = ['duh']
    amoji = '(â‰§ï¸¿â‰¦)'
  [amoji.dunnolol]
    words = ['dunno']
    amoji = 'Â¯\\(Â°_o)/Â¯'
  [amoji.ebola]
    words = ['ebola']
    amoji = 'á´‡Ê™á´ÊŸá´€'
  [amoji.ellipsis]
    words = ['ellipsis', '...']
    amoji = 'â€¦'
  [amoji.emdash]
    words = ['emdash', '--']
    amoji = 'â€“'
  [amoji.emptystar]
    words = ['emptystar']
    amoji = 'â˜†'
  [amoji.emptytriangle]
    words = ['emptytriangle', 't2']
    amoji = 'â–³'
  [amoji.endure]
    words = ['endure']
    amoji = '(Ò‚â—¡_â—¡) á•¤'
  [amoji.envelope]
    words = ['envelope', 'letter']
    amoji = 'âœ‰ï¸'
  [amoji.epsilon]
    words = ['epsilon']
    amoji = 'É›'
  [amoji.euro]
    words = ['euro']
    amoji = 'â‚¬'
  [amoji.evil]
    words = ['evil']
    amoji = 'Ïˆ(ï½€âˆ‡Â´)Ïˆ'
  [amoji.evillenny]
    words = ['evillenny']
    amoji = '(Í â‰– ÍœÊ–Í â‰–)'
  [amoji.execution]
    words = ['execution']
    amoji = '(âŒâ– _â– )ï¸»â•¦â•¤â”€   (â•¥ï¹â•¥)'
  [amoji.facebook]
    words = ['facebook']
    amoji = '(â•¯Â°â–¡Â°)â•¯ï¸µ ÊooqÇÉ”ÉÉŸ'
  [amoji.facepalm]
    words = ['facepalm']
    amoji = '(ï¼â€¸áƒš)'
  [amoji.fart]
    words = ['fart']
    amoji = '(Ë†âº«Ë†à¹‘)<3'
  [amoji.fight]
    words = ['fight']
    amoji = '(à¸‡ â€¢Ì€_â€¢Ì)à¸‡'
  [amoji.finn]
    words = ['finn']
    amoji = '| (â€¢ â—¡â€¢)|'
  [amoji.fish]
    words = ['fish']
    amoji = '<"(((<3'
  [amoji.five]
    words = ['5', 'five']
    amoji = 'åŒ'
  [amoji.fiveeights]
    words = ['5/8']
    amoji = 'â…'
  [amoji.flat]
    words = ['flat', 'bemolle']
    amoji = 'â™­'
  [amoji.flexing]
    words = ['flexing']
    amoji = 'á•™(`â–½Â´)á•—'
  [amoji.flipped]
    words = ['flipped', 'heavytable']
    amoji = 'â”¬â”€â”¬ï»¿ ï¸µ /(.â–¡. \\ï¼‰'
  [amoji.flower]
    words = ['flower', 'flor']
    amoji = '(âœ¿â— â€¿â— )'
  [amoji.flower2]
    words = ['f']
    amoji = 'âœ¿'
  [amoji.fly]
    words = ['fly']
    amoji = 'â”€=â‰¡Î£((( ã¤â—•Ù„Íœâ—•)ã¤'
  [amoji.friendflip]
    words = ['friendflip']
    amoji = '(â•¯Â°â–¡Â°)â•¯ï¸µ â”»â”â”» ï¸µ â•¯(Â°â–¡Â° â•¯)'
  [amoji.frown]
    words = ['frown']
    amoji = '(áƒ¦Ë˜âŒ£Ë˜áƒ¦)'
  [amoji.fuckoff]
    words = ['fuckoff', 'gtfo']
    amoji = 'à­§à¼¼à² ç›Šà² â•­âˆ©â•®à¼½'
  [amoji.fuckyou]
    words = ['fuckyou', 'fu']
    amoji = 'â”ŒĞŸâ”(à² _à² )'
  [amoji.gentleman]
    words = ['gentleman', 'sir', 'monocle']
    amoji = 'à² _à²°à³ƒ'
  [amoji.ghast]
    words = ['ghast']
    amoji = '= _ ='
  [amoji.ghost]
    words = ['ghost']
    amoji = 'à¼¼ ã¤ â_â à¼½ã¤'
  [amoji.gift]
    words = ['gift', 'present']
    amoji = '(Â´ãƒ»Ï‰ãƒ»)ã£ç”±'
  [amoji.gimme]
    words = ['gimme']
    amoji = 'à¼¼ ã¤ â—•_â—• à¼½ã¤'
  [amoji.glitterbomb]
    words = ['glitter']
    amoji = '(*ãƒ»â€¿ãƒ»)ãƒâŒ’*:ï½¥ï¾Ÿâœ§'
  [amoji.glasses]
    words = ['glasses']
    amoji = '(âŒ Í¡â–  ÍœÊ– Í¡â– )'
  [amoji.glassesoff]
    words = ['glassesoff']
    amoji = '( Í¡Â° ÍœÊ– Í¡Â°)ï¾‰âŒâ– -â– '
  [amoji.glitterderp]
    words = ['glitterderp']
    amoji = '(ï¾‰â˜‰ãƒ®âš†)ï¾‰ âŒ’*:ï½¥ï¾Ÿâœ§'
  [amoji.gloomy]
    words = ['gloomy']
    amoji = '(_ã‚œ_ã‚œ_)'
  [amoji.goatse]
    words = ['goatse']
    amoji = '(Ğ·à¹Îµ)'
  [amoji.gotit]
    words = ['gotit']
    amoji = '(â˜ï¾Ÿâˆ€ï¾Ÿ)â˜'
  [amoji.greet]
    words = ['greet', 'greetings']
    amoji = '( Â´â—” Ï‰â—”`) ãƒã‚·'
  [amoji.gun]
    words = ['gun', 'mg']
    amoji = 'ï¸»â•¦â•¤â”€'
  [amoji.hadouken]
    words = ['hadouken']
    amoji = 'à¼¼ã¤à² ç›Šà² à¼½ã¤ â”€=â‰¡Î£O))'
  [amoji.hammerandsickle]
    words = ['hammerandsickle', 'hs']
    amoji = 'â˜­'
  [amoji.handleft]
    words = ['handleft', 'hl']
    amoji = 'â˜œ'
  [amoji.handright]
    words = ['handright', 'hr']
    amoji = 'â˜'
  [amoji.haha]
    words = ['haha']
    amoji = 'Ù©(^â€¿^)Û¶'
  [amoji.happy]
    words = ['happy']
    amoji = 'Ù©( à¹‘â•¹ ê‡´â•¹)Û¶'
  [amoji.happygarry]
    words = ['happygarry']
    amoji = 'á••( á› )á•—'
  [amoji.heart]
    words = ['h', 'heart']
    amoji = 'â™¥'
  [amoji.hello]
    words = ['hello', 'ohai', 'bye']
    amoji = '(Ê˜â€¿Ê˜)â•¯'
  [amoji.highfive]
    words = ['highfive']
    amoji = '._.)/\\(._.'
  [amoji.hitting]
    words = ['hitting']
    amoji = '( ï½€çš¿Â´)ï½¡ï¾/'
  [amoji.hugs]
    words = ['hug', 'hugs']
    amoji = '(ã¥ï½¡â—•â€¿â€¿â—•ï½¡)ã¥'
  [amoji.iknowright]
    words = ['iknowright', 'ikr']
    amoji = 'â”ï½œï½¥à¸´Ï‰ï½¥à¸´#ï½œâ”Œ'
  [amoji.illuminati]
    words = ['illuminati']
    amoji = 'à­§(â–²á´—â–²)ãƒ'
  [amoji.infinity]
    words = ['infinity', 'inf']
    amoji = 'âˆ'
  [amoji.inlove]
    words = ['inlove']
    amoji = '(ã£Â´Ï‰`c)â™¡'
  [amoji.integral]
    words = ['int']
    amoji = 'âˆ«'
  [amoji.internet]
    words = ['internet']
    amoji = 'à¬˜(à©­*ËŠáµ•Ë‹)à©­*â€ŠÌ€Ë‹ ÉªÉ´á´›á´‡Ê€É´á´‡á´›'
  [amoji.interrobang]
    words = ['interrobang']
    amoji = 'â€½'
  [amoji.jake]
    words = ['jake']
    amoji = '(âá´¥âÊ‹)'
  [amoji.kawaii]
    words = ['kawaii']
    amoji = 'â‰§â—¡â‰¦'
  [amoji.keen]
    words = ['keen']
    amoji = 'â”¬â”´â”¬â”´â”¤ÆŸÍ†Ù„ÍœÆŸÍ† à¼½ï¾‰'
  [amoji.kiahh]
    words = ['kiahh']
    amoji = '~\\(â‰§â–½â‰¦)/~'
  [amoji.kiss]
    words = ['kiss']
    amoji = '(ã¥ ï¿£ Â³ï¿£)ã¥'
  [amoji.kyubey]
    words = ['kyubey']
    amoji = 'ï¼äººâ—• â€¿â€¿ â—•äººï¼¼'
  [amoji.lambda]
    words = ['lambda']
    amoji = 'Î»'
  [amoji.lazy]
    words = ['lazy']
    amoji = '_(:3ã€âˆ )_'
  [amoji.left]
    words = ['left', '<-']
    amoji = 'â†'
  [amoji.lenny]
    words = ['lenny']
    amoji = '( Í¡Â° ÍœÊ– Í¡Â°)'
  [amoji.lennybill]
    words = ['lennybill']
    amoji = '[Ì²Ì…$Ì²Ì…(Ì²Ì… Í¡Â° ÍœÊ– Í¡Â°Ì²Ì…)Ì²Ì…$Ì²Ì…]'
  [amoji.lennyfight]
    words = ['lennyfight']
    amoji = '(à¸‡ Í Â° ÍŸÊ– Í¡Â°)à¸‡'
  [amoji.lennyflip]
    words = ['lennyflip']
    amoji = '(ãƒ Í¡Â° ÍœÊ– Í¡Â°ãƒ)   ï¸µ ( Íœã€‚ Í¡Ê– Íœã€‚)'
  [amoji.lennygang]
    words = ['lennygang']
    amoji = '( Í¡Â°( Í¡Â° ÍœÊ–( Í¡Â° ÍœÊ– Í¡Â°)Ê– Í¡Â°) Í¡Â°)'
  [amoji.lennyshrug]
    words = ['lennyshrug']
    amoji = 'Â¯\\_( Í¡Â° ÍœÊ– Í¡Â°)_/Â¯'
  [amoji.lennysir]
    words = ['lennysir']
    amoji = '( à²  ÍœÊ– à²°à³ƒ)'
  [amoji.lennystalker]
    words = ['lennystalker']
    amoji = 'â”¬â”´â”¬â”´â”¤( Í¡Â° ÍœÊ–â”œâ”¬â”´â”¬â”´'
  [amoji.lennystrong]
    words = ['lennystrong']
    amoji = 'á•¦( Í¡Â° ÍœÊ– Í¡Â°)á•¤'
  [amoji.lennywizard]
    words = ['lennywizard']
    amoji = 'â•°( Í¡Â° ÍœÊ– Í¡Â° )ã¤â”€â”€â˜†*:ãƒ»ï¾Ÿ'
  [amoji.lol]
    words = ['lol']
    amoji = 'L(Â° O Â°L)'
  [amoji.look]
    words = ['look']
    amoji = '(à²¡_à²¡)â˜'
  [amoji.love]
    words = ['love']
    amoji = 'â™¥â€¿â™¥'
  [amoji.lovebear]
    words = ['lovebear']
    amoji = 'Ê•â™¥á´¥â™¥Ê”'
  [amoji.lumpy]
    words = ['lumpy']
    amoji = 'ê’° ê’¡âŒ“ê’¡ê’±'
  [amoji.luv]
    words = ['luv']
    amoji = '-`áƒ¦Â´-'
  [amoji.magic]
    words = ['magic']
    amoji = 'ãƒ½(ï½€Ğ”Â´)âŠƒâ”â˜†ï¾Ÿ. * ï½¥ ï½¡ï¾Ÿ,'
  [amoji.magicflip]
    words = ['magicflip']
    amoji = '(/Â¯â—¡ â€¿ â—¡)/Â¯ ~ â”»â”â”»'
  [amoji.meep]
    words = ['meep']
    amoji = '\\(Â°^Â°)/'
  [amoji.meh]
    words = ['meh']
    amoji = 'à² _à² '
  [amoji.mistyeyes]
    words = ['mistyeyes']
    amoji = 'à²¡_à²¡'
  [amoji.monster]
    words = ['monster']
    amoji = 'à¼¼ à¼àº¶ à·´ à¼àº¶à¼½'
  [amoji.natural]
    words = ['natural']
    amoji = 'â™®'
  [amoji.needle]
    words = ['needle', 'inject']
    amoji = 'â”Œ(â—‰ ÍœÊ–â—‰)ã¤â”£â–‡â–‡â–‡â•â”€â”€'
  [amoji.nice]
    words = ['nice']
    amoji = '( Í¡Â° Íœ Â°)'
  [amoji.no]
    words = ['no']
    amoji = 'â†’_â†'
  [amoji.noclue]
    words = ['noclue']
    amoji = 'ï¼äººâ—• __ â—•äººï¼¼'
  [amoji.nom]
    words = ['nom', 'yummy', 'delicious']
    amoji = '(ã£Ë†Ú¡Ë†Ï‚)'
  [amoji.note]
    words = ['note', 'sing']
    amoji = 'â™«'
  [amoji.nuclear]
    words = ['nuclear', 'radioactive', 'nukular']
    amoji = 'â˜¢'
  [amoji.nyan]
    words = ['nyan']
    amoji = '~=[,,_,,]:3'
  [amoji.nyeh]
    words = ['nyeh']
    amoji = '@^@'
  [amoji.ohshit]
    words = ['ohshit']
    amoji = '( Âºï¹ƒÂº )'
  [amoji.omg]
    words = ['omg']
    amoji = 'â—•_â—•'
  [amoji.oneeighth]
    words = ['1/8']
    amoji = 'â…›'
  [amoji.onefourth]
    words = ['1/4']
    amoji = 'Â¼'
  [amoji.onehalf]
    words = ['1/2']
    amoji = 'Â½'
  [amoji.onethird]
    words = ['1/3']
    amoji = 'â…“'
  [amoji.option]
    words = ['opt', 'option']
    amoji = 'âŒ¥'
  [amoji.ohreally]
    words = ['orly']
    amoji = '(ëˆˆ_ëˆˆ)'
  [amoji.ohyou]
    words = ['ohyou', 'ou']
    amoji = '(â—à°¥à±ªà°¥)á´–'
  [amoji.peace]
    words = ['peace', 'victory']
    amoji = 'âœŒ(-â€¿-)âœŒ'
  [amoji.pear]
    words = ['pear']
    amoji = '(__>-'
  [amoji.pi]
    words = ['pi']
    amoji = 'Ï€'
  [amoji.pingpong]
    words = ['pingpong']
    amoji = '( â€¢_â€¢)O*Â¯`Â·.Â¸.Â·Â´Â¯`Â°Q(â€¢_â€¢ )'
  [amoji.plain]
    words = ['plain']
    amoji = '._.'
  [amoji.pleased]
    words = ['pleased']
    amoji = '(Ë¶â€¾á·„ â»Ì« â€¾á·…Ëµ)'
  [amoji.point]
    words = ['point']
    amoji = '(â˜ï¾Ÿãƒ®ï¾Ÿ)â˜'
  [amoji.pooh]
    words = ['pooh']
    amoji = 'Ê• â€¢ÌØˆâ€¢Ì€)'
  [amoji.pound]
    words = ['pound']
    amoji = 'Â£'
  [amoji.praise]
    words = ['praise']
    amoji = '(â˜ Õà¨Š Õ)â˜'
  #[amoji.punch]
  #  words = ['punch']
  #  amoji = 'O=(\'-\'Q)'
  [amoji.rage]
    words = ['rage', 'mad']
    amoji = 't(à² ç›Šà² t)'
  [amoji.rageflip]
    words = ['rageflip']
    amoji = '(ãƒà² ç›Šà² )ãƒå½¡â”»â”â”»'
  [amoji.rainbowcat]
    words = ['rainbowcat']
    amoji = '(=^ï½¥ï½ªï½¥^=))ï¾‰å½¡â˜†'
  [amoji.really]
    words = ['really']
    amoji = 'Ã²_Ã´'
  [amoji.registered]
    words = ['r']
    amoji = 'Â®'
  [amoji.right]
    words = ['right', '->']
    amoji = 'â†’'
  [amoji.riot]
    words = ['riot']
    amoji = 'à­§à¼¼à² ç›Šà² à¼½à­¨'
  [amoji.rolleyes]
    words = ['rolleyes']
    amoji = '(â—”_â—”)'
  [amoji.rose ]
    words = ['rose']
    amoji = 'âœ¿Ú¿Ú°Û£â€”'
  [amoji.run]
    words = ['run']
    amoji = '(â•¯Â°â–¡Â°)â•¯'
  [amoji.sad]
    words = ['sad']
    amoji = 'Îµ(Â´ï­ï¸µï­`)Ğ·'
  [amoji.saddonger]
    words = ['saddonger']
    amoji = 'ãƒ½à¼¼àºˆÊ–Ì¯àºˆà¼½ï¾‰'
  [amoji.sadlenny]
    words = ['sadlenny']
    amoji = '( Í¡Â° Ê–Ì¯ Í¡Â°)'
  [amoji.seveneigths]
    words = ['7/8']
    amoji = 'â…'
  [amoji.sharp]
    words = ['sharp', 'diesis']
    amoji = 'â™¯'
  [amoji.shout]
    words = ['shout']
    amoji = 'â•š(â€¢âŒ‚â€¢)â•'
  [amoji.shrug]
    words = ['shrug']
    amoji = 'Â¯\\_(ãƒ„)_/Â¯'
  [amoji.shy]
    words = ['shy']
    amoji = '=^_^='
  [amoji.sigma]
    words = ['sigma', 'sum']
    amoji = 'Î£'
  [amoji.skull]
    words = ['skull']
    amoji = 'â˜ '
  [amoji.smile]
    words = ['smile']
    amoji = 'ãƒ„'
  [amoji.smiley]
    words = ['smiley']
    amoji = 'â˜ºï¸'
  [amoji.smirk]
    words = ['smirk']
    amoji = 'Â¬â€¿Â¬'
  [amoji.snowman]
    words = ['snowman']
    amoji = 'â˜ƒ'
  [amoji.sob]
    words = ['sob']
    amoji = '(;Â´à¼àº¶Ğ”à¼àº¶`)'
  [amoji.spade]
    words = ['spade']
    amoji = 'â™ '
  [amoji.squareroot]
    words = ['sqrt']
    amoji = 'âˆš'
  [amoji.squid]
    words = ['squid']
    amoji = '<ã‚³:å½¡'
  [amoji.star]
    words = ['star']
    amoji = 'â˜…'
  [amoji.strong]
    words = ['strong']
    amoji = 'á•™(â‡€â€¸â†¼â€¶)á•—'
  [amoji.suicide]
    words = ['suicide']
    amoji = 'Îµ/ÌµÍ‡Ì¿Ì¿/â€™Ì¿â€™Ì¿ Ì¿(â—¡ï¸µâ—¡)'
  [amoji.sum]
    words = ['sum']
    amoji = 'âˆ‘'
  [amoji.sun]
    words = ['sun']
    amoji = 'â˜€'
  [amoji.surprised]
    words = ['surprised']
    amoji = '(à¹‘â€¢Ì ãƒ® â€¢Ì€à¹‘)'
  [amoji.surrender]
    words = ['surrender']
    amoji = '\\_(-_-)_/'
  [amoji.stalker]
    words = ['stalker']
    amoji = 'â”¬â”´â”¬â”´â”¤(ï½¥_â”œâ”¬â”´â”¬â”´'
  [amoji.swag]
    words = ['swag']
    amoji = '(Ì¿â–€Ì¿â€¿â€‰Ì¿â–€Ì¿ Ì¿)'
  [amoji.sword]
    words = ['sword']
    amoji = 'o()xxxx[{::::::::::::::::::>'
  [amoji.tabledown]
    words = ['tabledown']
    amoji = 'â”¬â”€â”¬ï»¿ ãƒ( ã‚œ-ã‚œãƒ)'
  [amoji.tableflip]
    words = ['tableflip']
    amoji = '(ãƒ ã‚œĞ”ã‚œ)ãƒ ï¸µ â”»â”â”»'
  [amoji.tau]
    words = ['tau']
    amoji = 'Ï„'
  [amoji.tears]
    words = ['tears']
    amoji = '(à²¥ï¹à²¥)'
  [amoji.terrorist]
    words = ['terrorist']
    amoji = 'à­§à¼¼à² ç›Šà² à¼½ï¸»â•¦â•¤â”€'
  [amoji.thanks]
    words = ['thanks', 'thankyou', 'ty']
    amoji = '\\(^-^)/'
  [amoji.therefore]
    words = ['therefore', 'so']
    amoji = 'â¸«'
  [amoji.threeeights]
    words = ['3/8']
    amoji = 'â…œ'
  [amoji.tiefighter]
    words = ['tiefighter']
    amoji = '|=-(Â¤)-=|'
  [amoji.tired]
    words = ['tired']
    amoji = '(=____=)'
  [amoji.toldyouso]
    words = ['toldyouso', 'toldyou']
    amoji = 'â˜œ(ê’¡âŒ“ê’¡)'
  [amoji.toogood]
    words = ['toogood']
    amoji = 'á•¦(Ã²á´¥Ã³)á•¥'
  [amoji.trademark]
    words = ['tm']
    amoji = 'â„¢'
  [amoji.triangle]
    words = ['triangle', 't']
    amoji = 'â–²'
  [amoji.twothirds]
    words = ['2/3']
    amoji = 'â…”'
  [amoji.unflip]
    words = ['unflip']
    amoji = 'â”¬â”€â”€â”¬ ãƒ(Ã²_Ã³ãƒ)'
  [amoji.up]
    words = ['up']
    amoji = 'â†‘'
  [amoji.victory]
    words = ['victory']
    amoji = '(à¹‘â€¢Ì€ã…‚â€¢Ì)à¸‡âœ§'
  [amoji.wat]
    words = ['wat']
    amoji = '(Ã’Ğ”Ã“×±)'
  [amoji.wave]
    words = ['wave']
    amoji = '( * ^ *) ãƒã‚·'
  [amoji.whaa]
    words = ['whaa']
    amoji = 'Ã–'
  [amoji.whistle]
    words = ['whistle']
    amoji = '(ã£^Ğ·^)â™ªâ™¬'
  [amoji.whoa]
    words = ['whoa']
    amoji = '(Â°oâ€¢)'
  [amoji.why]
    words = ['why']
    amoji = 'áƒš(`â—‰â—à±ªâ—Ÿâ—‰â€µáƒš)'
  [amoji.woo]
    words = ['woo']
    amoji = 'ï¼¼(ï¼¾Oï¼¾)ï¼'
  [amoji.wtf]
    words = ['wtf']
    amoji = '''(âŠ™ï¼¿âŠ™\')'''
  [amoji.wut]
    words = ['wut']
    amoji = 'âŠ™Ï‰âŠ™'
  [amoji.yay]
    words = ['yay']
    amoji = '\\( ï¾Ÿãƒ®ï¾Ÿ)/'
  [amoji.yeah]
    words = ['yeah', 'yes']
    amoji = '(â€¢Ì€á´—â€¢Ì)Ùˆ Ì‘Ì‘'
  [amoji.yen]
    words = ['yen']
    amoji = 'Â¥'
  [amoji.yinyang]
    words = ['yinyang', 'yy']
    amoji = 'â˜¯'
  [amoji.yolo]
    words = ['yolo']
    amoji = 'Yáµ’áµ˜ Oá¶°Ë¡Ê¸ Lá¶¤áµ›áµ‰ Oá¶°á¶œáµ‰'
  [amoji.youkids]
    words = ['youkids', 'ukids']
    amoji = 'áƒšà¼¼>â•­ ÍŸÊ–â•®<à¼½áƒš'
  [amoji.yuno]
    words = ['y u no', 'yuno']
    amoji = '(å±®ï¾ŸĞ”ï¾Ÿ)å±® Y U NO'
  [amoji.zen]
    words = ['zen', 'meditation', 'omm']
    amoji = 'âŠ¹â•°(âŒ£ÊŸâŒ£)â•¯âŠ¹'
  [amoji.zoidberg]
    words = ['zoidberg']
    amoji = '(V) (Â°,,,,Â°) (V)'
  [amoji.zombie]
    words = ['zombie']
    amoji = '[Â¬Âº-Â°]Â¬'
