[multi]
  [multi.acid]
    words = ['acid']
    multi = 'âŠ‚(â—‰â€¿â—‰)ã¤'
  [multi.afraid]
    words = ['afraid']
    multi = '(ã†† _ ã††)'
  [multi.angel]
    words = ['angel']
    multi = 'â˜œ(âŒ’â–½âŒ’)â˜'
  [multi.angry]
    words = ['angry']
    multi = 'â€¢`_Â´â€¢'
  [multi.arrowhead]
    words = ['arrowhead']
    multi = 'â¤œ(â±º Ê–Ì¯â±º)â¤'
  [multi.apple]
    words = ['apple']
    multi = 'ï£¿'
  [multi.ass]
    words = ['ass', 'butt']
    multi = '(â€¿|â€¿)'
  [multi.awkward]
    words = ['awkward']
    multi = 'â€¢Í¡Ë˜ã‡â€¢Í¡Ë˜'
  [multi.bat]
    words = ['bat']
    multi = '/|\\ ^._.^ /|\\'
  [multi.bear]
    words = ['bear', 'koala']
    multi = 'Ê•Â·Í¡á´¥Â·Ê”ï»¿'
  [multi.bearflip]
    words = ['bearflip']
    multi = 'Ê•ãƒâ€¢á´¥â€¢Ê”ãƒ ï¸µ â”»â”â”»'
  [multi.bearhug]
    words = ['bearhug']
    multi = 'Ê•ã£â€¢á´¥â€¢Ê”ã£'
  [multi.because]
    words = ['because', 'since']
    multi = 'âˆµ'
  [multi.bigheart]
    words = ['bigheart']
    multi = 'â¤'
  [multi.blackeye]
    words = ['blackeye']
    multi = '0__#'
  [multi.blubby]
    words = ['blubby']
    multi = '(      0    _   0    )'
  [multi.blush]
    words = ['blush']
    multi = '(Ëµ Í¡Â° ÍœÊ– Í¡Â°Ëµ)'
  [multi.bond]
    words = ['bond', '007']
    multi = 'â”Œ( ÍÂ° ÍœÊ–Í¡Â°)=Îµ/ÌµÍ‡Ì¿Ì¿/â€™Ì¿â€™Ì¿ Ì¿'
  [multi.boobs]
    words = ['boobs']
    multi = '( . Y . )'
  [multi.bored]
    words = ['bored']
    multi = '(-_-)'
  [multi.bribe]
    words = ['bribe']
    multi = '( â€¢Í¡Ë˜ _â€¢Í¡Ë˜)ãƒÃ°'
  [multi.bubbles]
    words = ['bubbles']
    multi = '( Ë˜ Â³Ë˜)ãƒÂ°ï¾ŸÂºâï½¡'
  [multi.butterfly]
    words = ['butterfly']
    multi = 'Æ¸ÓœÆ·'
  [multi.cat]
    words = ['cat']
    multi = '(= Ğ¤ã‚§Ğ¤=)'
  [multi.catlenny]
    words = ['catlenny']
    multi = '( Í¡Â° á´¥ Í¡Â°)ï»¿'
  [multi.checkmark]
    words = ['check']
    multi = 'âœ“'
  [multi.chubby]
    words = ['chubby']
    multi = 'â•­(Ê˜Ì†~â—à±ªâ—Ÿ~Ê˜Ì†)â•®'
  [multi.claro]
    words = ['claro']
    multi = '(Í¡ Â° ÍœÊ– Í¡ Â°)'
  [multi.clique]
    words = ['clique', 'gang', 'squad']
    multi = 'ãƒ½à¼¼ àºˆÙ„Íœàºˆà¼¼ â–€Ì¿Ì¿Ä¹Ì¯Ì¿Ì¿â–€Ì¿ Ì¿à¼½ÆŸÍ†Ù„ÍœÆŸÍ† à¼½ï¾‰'
  [multi.cloud]
    words = ['cloud']
    multi = 'â˜'
  [multi.club]
    words = ['club']
    multi = 'â™£'
  [multi.coffee]
    words = ['coffee', 'cuppa']
    multi = 'c[_]'
  [multi.command]
    words = ['cmd', 'command']
    multi = 'âŒ˜'
  [multi.cool]
    words = ['cool', 'csi']
    multi = '(â€¢_â€¢) ( â€¢_â€¢)>âŒâ– -â–  (âŒâ– _â– )'
  [multi.copyright]
    words = ['copy','c']
    multi = 'Â©'
  [multi.creep]
    words = ['creep']
    multi = 'Ô…(â‰–â€¿â‰–Ô…)'
  [multi.creepcute]
    words = ['creepcute']
    multi = 'Æª(Ú“×²)â€Æªâ€‹â€‹'
  [multi.crim3s]
    words = ['crim3s']
    multi = '( âœœï¸µâœœ )'
  [multi.cross]
    words = ['cross']
    multi = 'â€ '
  [multi.cry]
    words = ['cry']
    multi = '(â•¥ï¹â•¥)'
  [multi.crywave]
    words = ['crywave']
    multi = '( â•¥ï¹â•¥) ãƒã‚·'
  [multi.cute]
    words = ['cute']
    multi = '(ï½¡â—•â€¿â€¿â—•ï½¡)'
  [multi.d1]
    words = ['d1']
    multi = 'âš€'
  [multi.d2]
    words = ['d2']
    multi = 'âš'
  [multi.d3]
    words = ['d3']
    multi = 'âš‚'
  [multi.d4]
    words = ['d4']
    multi = 'âšƒ'
  [multi.d5]
    words = ['d5']
    multi = 'âš„'
  [multi.d6]
    words = ['d6']
    multi = 'âš…'
  [multi.damnyou]
    words = ['damnyou']
    multi = '(á•— Í Â° à¨Š Í Â° )á•—'
  [multi.dance]
    words = ['dance']
    multi = 'á••(âŒâ– _â– )á•— â™ªâ™¬'
  [multi.dead]
    words = ['dead']
    multi = 'xâ¸‘x'
  [multi.dealwithit]
    words = ['dealwithit', 'dwi']
    multi = '(âŒâ– _â– )'
  [multi.delta]
    words = ['delta']
    multi = 'Î”'
  [multi.depressed]
    words = ['depressed']
    multi = '(ï¸¶ï¸¹ï¸¶)'
  [multi.derp]
    words = ['derp']
    multi = 'â˜‰ â€¿ âš†'
  [multi.diamond]
    words = ['diamond']
    multi = 'â™¦'
  [multi.dog]
    words = ['dog']
    multi = '(â—•á´¥â—•Ê‹)'
  [multi.dollar]
    words = ['dollar']
    multi = '$'
  [multi.dong]
    words = ['dong']
    multi = '(Ì¿â–€Ì¿â€‰Ì¿Ä¹Ì¯Ì¿Ì¿â–€Ì¿ Ì¿)Ì„'
  [multi.donger]
    words = ['donger']
    multi = 'ãƒ½à¼¼àºˆÙ„Íœàºˆà¼½ï¾‰'
  [multi.dontcare]
    words = ['dontcare']
    multi = 'â•­âˆ©â•®ï¼ˆï¸¶ï¸¿ï¸¶ï¼‰â•­âˆ©â•®'
  [multi.donotwant]
    words = ['do not want', 'dontwant']
    multi = 'ãƒ½(ï½€Ğ”Â´)ï¾‰'
  [multi.dope]
    words = ['dope']
    multi = '<(^_^)>'
  [multi.doublequotesleft]
    words = ['<<']
    multi = 'Â«'
  [multi.doublequotesright]
    words = ['>>']
    multi = 'Â»'
  [multi.doubleflat]
    words = ['doubleflat']
    multi = 'ğ„«'
  [multi.doublesharp]
    words = ['doublesharp']
    multi = 'ğ„ª'
  [multi.doubletableflip]
    words = ['doubletableflip']
    multi = 'â”»â”â”» ï¸µãƒ½(`Ğ”Â´)ï¾‰ï¸µ â”»â”â”»'
  [multi.down]
    words = ['down']
    multi = 'â†“'
  [multi.duckface]
    words = ['duckface']
    multi = '(ãƒ»3ãƒ»)'
  [multi.duel]
    words = ['duel']
    multi = 'á••(â•­à²°â•­ ÍŸÊ–â•®â€¢Ì)âŠƒÂ¤=(â€”â€”â€”â€”-'
  [multi.duh]
    words = ['duh']
    multi = '(â‰§ï¸¿â‰¦)'
  [multi.dunnolol]
    words = ['dunno']
    multi = 'Â¯\\(Â°_o)/Â¯'
  [multi.ebola]
    words = ['ebola']
    multi = 'á´‡Ê™á´ÊŸá´€'
  [multi.ellipsis]
    words = ['ellipsis', '...']
    multi = 'â€¦'
  [multi.emdash]
    words = ['emdash', '--']
    multi = 'â€“'
  [multi.emptystar]
    words = ['emptystar']
    multi = 'â˜†'
  [multi.emptytriangle]
    words = ['emptytriangle', 't2']
    multi = 'â–³'
  [multi.endure]
    words = ['endure']
    multi = '(Ò‚â—¡_â—¡) á•¤'
  [multi.envelope]
    words = ['envelope', 'letter']
    multi = 'âœ‰ï¸'
  [multi.epsilon]
    words = ['epsilon']
    multi = 'É›'
  [multi.euro]
    words = ['euro']
    multi = 'â‚¬'
  [multi.evil]
    words = ['evil']
    multi = 'Ïˆ(ï½€âˆ‡Â´)Ïˆ'
  [multi.evillenny]
    words = ['evillenny']
    multi = '(Í â‰– ÍœÊ–Í â‰–)'
  [multi.execution]
    words = ['execution']
    multi = '(âŒâ– _â– )ï¸»â•¦â•¤â”€   (â•¥ï¹â•¥)'
  [multi.facebook]
    words = ['facebook']
    multi = '(â•¯Â°â–¡Â°)â•¯ï¸µ ÊooqÇÉ”ÉÉŸ'
  [multi.facepalm]
    words = ['facepalm']
    multi = '(ï¼â€¸áƒš)'
  [multi.fart]
    words = ['fart']
    multi = '(Ë†âº«Ë†à¹‘)<3'
  [multi.fight]
    words = ['fight']
    multi = '(à¸‡ â€¢Ì€_â€¢Ì)à¸‡'
  [multi.finn]
    words = ['finn']
    multi = '| (â€¢ â—¡â€¢)|'
  [multi.fish]
    words = ['fish']
    multi = '<"(((<3'
  [multi.five]
    words = ['5', 'five']
    multi = 'åŒ'
  [multi.fiveeights]
    words = ['5/8']
    multi = 'â…'
  [multi.flat]
    words = ['flat', 'bemolle']
    multi = 'â™­'
  [multi.flexing]
    words = ['flexing']
    multi = 'á•™(`â–½Â´)á•—'
  [multi.flipped]
    words = ['flipped', 'heavytable']
    multi = 'â”¬â”€â”¬ï»¿ ï¸µ /(.â–¡. \\ï¼‰'
  [multi.flower]
    words = ['flower', 'flor']
    multi = '(âœ¿â— â€¿â— )'
  [multi.flower2]
    words = ['f']
    multi = 'âœ¿'
  [multi.fly]
    words = ['fly']
    multi = 'â”€=â‰¡Î£((( ã¤â—•Ù„Íœâ—•)ã¤'
  [multi.friendflip]
    words = ['friendflip']
    multi = '(â•¯Â°â–¡Â°)â•¯ï¸µ â”»â”â”» ï¸µ â•¯(Â°â–¡Â° â•¯)'
  [multi.frown]
    words = ['frown']
    multi = '(áƒ¦Ë˜âŒ£Ë˜áƒ¦)'
  [multi.fuckoff]
    words = ['fuckoff', 'gtfo']
    multi = 'à­§à¼¼à² ç›Šà² â•­âˆ©â•®à¼½'
  [multi.fuckyou]
    words = ['fuckyou', 'fu']
    multi = 'â”ŒĞŸâ”(à² _à² )'
  [multi.gentleman]
    words = ['gentleman', 'sir', 'monocle']
    multi = 'à² _à²°à³ƒ'
  [multi.ghast]
    words = ['ghast']
    multi = '= _ ='
  [multi.ghost]
    words = ['ghost']
    multi = 'à¼¼ ã¤ â_â à¼½ã¤'
  [multi.gift]
    words = ['gift', 'present']
    multi = '(Â´ãƒ»Ï‰ãƒ»)ã£ç”±'
  [multi.gimme]
    words = ['gimme']
    multi = 'à¼¼ ã¤ â—•_â—• à¼½ã¤'
  [multi.glitterbomb]
    words = ['glitter']
    multi = '(*ãƒ»â€¿ãƒ»)ãƒâŒ’*:ï½¥ï¾Ÿâœ§'
  [multi.glasses]
    words = ['glasses']
    multi = '(âŒ Í¡â–  ÍœÊ– Í¡â– )'
  [multi.glassesoff]
    words = ['glassesoff']
    multi = '( Í¡Â° ÍœÊ– Í¡Â°)ï¾‰âŒâ– -â– '
  [multi.glitterderp]
    words = ['glitterderp']
    multi = '(ï¾‰â˜‰ãƒ®âš†)ï¾‰ âŒ’*:ï½¥ï¾Ÿâœ§'
  [multi.gloomy]
    words = ['gloomy']
    multi = '(_ã‚œ_ã‚œ_)'
  [multi.goatse]
    words = ['goatse']
    multi = '(Ğ·à¹Îµ)'
  [multi.gotit]
    words = ['gotit']
    multi = '(â˜ï¾Ÿâˆ€ï¾Ÿ)â˜'
  [multi.greet]
    words = ['greet', 'greetings']
    multi = '( Â´â—” Ï‰â—”`) ãƒã‚·'
  [multi.gun]
    words = ['gun', 'mg']
    multi = 'ï¸»â•¦â•¤â”€'
  [multi.hadouken]
    words = ['hadouken']
    multi = 'à¼¼ã¤à² ç›Šà² à¼½ã¤ â”€=â‰¡Î£O))'
  [multi.hammerandsickle]
    words = ['hammerandsickle', 'hs']
    multi = 'â˜­'
  [multi.handleft]
    words = ['handleft', 'hl']
    multi = 'â˜œ'
  [multi.handright]
    words = ['handright', 'hr']
    multi = 'â˜'
  [multi.haha]
    words = ['haha']
    multi = 'Ù©(^â€¿^)Û¶'
  [multi.happy]
    words = ['happy']
    multi = 'Ù©( à¹‘â•¹ ê‡´â•¹)Û¶'
  [multi.happygarry]
    words = ['happygarry']
    multi = 'á••( á› )á•—'
  [multi.heart]
    words = ['h', 'heart']
    multi = 'â™¥'
  [multi.hello]
    words = ['hello', 'ohai', 'bye']
    multi = '(Ê˜â€¿Ê˜)â•¯'
  [multi.highfive]
    words = ['highfive']
    multi = '._.)/\\(._.'
  [multi.hitting]
    words = ['hitting']
    multi = '( ï½€çš¿Â´)ï½¡ï¾/'
  [multi.hugs]
    words = ['hug', 'hugs']
    multi = '(ã¥ï½¡â—•â€¿â€¿â—•ï½¡)ã¥'
  [multi.iknowright]
    words = ['iknowright', 'ikr']
    multi = 'â”ï½œï½¥à¸´Ï‰ï½¥à¸´#ï½œâ”Œ'
  [multi.illuminati]
    words = ['illuminati']
    multi = 'à­§(â–²á´—â–²)ãƒ'
  [multi.infinity]
    words = ['infinity', 'inf']
    multi = 'âˆ'
  [multi.inlove]
    words = ['inlove']
    multi = '(ã£Â´Ï‰`c)â™¡'
  [multi.integral]
    words = ['int']
    multi = 'âˆ«'
  [multi.internet]
    words = ['internet']
    multi = 'à¬˜(à©­*ËŠáµ•Ë‹)à©­*â€ŠÌ€Ë‹ ÉªÉ´á´›á´‡Ê€É´á´‡á´›'
  [multi.interrobang]
    words = ['interrobang']
    multi = 'â€½'
  [multi.jake]
    words = ['jake']
    multi = '(âá´¥âÊ‹)'
  [multi.kawaii]
    words = ['kawaii']
    multi = 'â‰§â—¡â‰¦'
  [multi.keen]
    words = ['keen']
    multi = 'â”¬â”´â”¬â”´â”¤ÆŸÍ†Ù„ÍœÆŸÍ† à¼½ï¾‰'
  [multi.kiahh]
    words = ['kiahh']
    multi = '~\\(â‰§â–½â‰¦)/~'
  [multi.kiss]
    words = ['kiss']
    multi = '(ã¥ ï¿£ Â³ï¿£)ã¥'
  [multi.kyubey]
    words = ['kyubey']
    multi = 'ï¼äººâ—• â€¿â€¿ â—•äººï¼¼'
  [multi.lambda]
    words = ['lambda']
    multi = 'Î»'
  [multi.lazy]
    words = ['lazy']
    multi = '_(:3ã€âˆ )_'
  [multi.left]
    words = ['left', '<-']
    multi = 'â†'
  [multi.lenny]
    words = ['lenny']
    multi = '( Í¡Â° ÍœÊ– Í¡Â°)'
  [multi.lennybill]
    words = ['lennybill']
    multi = '[Ì²Ì…$Ì²Ì…(Ì²Ì… Í¡Â° ÍœÊ– Í¡Â°Ì²Ì…)Ì²Ì…$Ì²Ì…]'
  [multi.lennyfight]
    words = ['lennyfight']
    multi = '(à¸‡ Í Â° ÍŸÊ– Í¡Â°)à¸‡'
  [multi.lennyflip]
    words = ['lennyflip']
    multi = '(ãƒ Í¡Â° ÍœÊ– Í¡Â°ãƒ)   ï¸µ ( Íœã€‚ Í¡Ê– Íœã€‚)'
  [multi.lennygang]
    words = ['lennygang']
    multi = '( Í¡Â°( Í¡Â° ÍœÊ–( Í¡Â° ÍœÊ– Í¡Â°)Ê– Í¡Â°) Í¡Â°)'
  [multi.lennyshrug]
    words = ['lennyshrug']
    multi = 'Â¯\\_( Í¡Â° ÍœÊ– Í¡Â°)_/Â¯'
  [multi.lennysir]
    words = ['lennysir']
    multi = '( à²  ÍœÊ– à²°à³ƒ)'
  [multi.lennystalker]
    words = ['lennystalker']
    multi = 'â”¬â”´â”¬â”´â”¤( Í¡Â° ÍœÊ–â”œâ”¬â”´â”¬â”´'
  [multi.lennystrong]
    words = ['lennystrong']
    multi = 'á•¦( Í¡Â° ÍœÊ– Í¡Â°)á•¤'
  [multi.lennywizard]
    words = ['lennywizard']
    multi = 'â•°( Í¡Â° ÍœÊ– Í¡Â° )ã¤â”€â”€â˜†*:ãƒ»ï¾Ÿ'
  [multi.lol]
    words = ['lol']
    multi = 'L(Â° O Â°L)'
  [multi.look]
    words = ['look']
    multi = '(à²¡_à²¡)â˜'
  [multi.love]
    words = ['love']
    multi = 'â™¥â€¿â™¥'
  [multi.lovebear]
    words = ['lovebear']
    multi = 'Ê•â™¥á´¥â™¥Ê”'
  [multi.lumpy]
    words = ['lumpy']
    multi = 'ê’° ê’¡âŒ“ê’¡ê’±'
  [multi.luv]
    words = ['luv']
    multi = '-`áƒ¦Â´-'
  [multi.magic]
    words = ['magic']
    multi = 'ãƒ½(ï½€Ğ”Â´)âŠƒâ”â˜†ï¾Ÿ. * ï½¥ ï½¡ï¾Ÿ,'
  [multi.magicflip]
    words = ['magicflip']
    multi = '(/Â¯â—¡ â€¿ â—¡)/Â¯ ~ â”»â”â”»'
  [multi.meep]
    words = ['meep']
    multi = '\\(Â°^Â°)/'
  [multi.meh]
    words = ['meh']
    multi = 'à² _à² '
  [multi.mistyeyes]
    words = ['mistyeyes']
    multi = 'à²¡_à²¡'
  [multi.monster]
    words = ['monster']
    multi = 'à¼¼ à¼àº¶ à·´ à¼àº¶à¼½'
  [multi.natural]
    words = ['natural']
    multi = 'â™®'
  [multi.needle]
    words = ['needle', 'inject']
    multi = 'â”Œ(â—‰ ÍœÊ–â—‰)ã¤â”£â–‡â–‡â–‡â•â”€â”€'
  [multi.nice]
    words = ['nice']
    multi = '( Í¡Â° Íœ Â°)'
  [multi.no]
    words = ['no']
    multi = 'â†’_â†'
  [multi.noclue]
    words = ['noclue']
    multi = 'ï¼äººâ—• __ â—•äººï¼¼'
  [multi.nom]
    words = ['nom', 'yummy', 'delicious']
    multi = '(ã£Ë†Ú¡Ë†Ï‚)'
  [multi.note]
    words = ['note', 'sing']
    multi = 'â™«'
  [multi.nuclear]
    words = ['nuclear', 'radioactive', 'nukular']
    multi = 'â˜¢'
  [multi.nyan]
    words = ['nyan']
    multi = '~=[,,_,,]:3'
  [multi.nyeh]
    words = ['nyeh']
    multi = '@^@'
  [multi.ohshit]
    words = ['ohshit']
    multi = '( Âºï¹ƒÂº )'
  [multi.omg]
    words = ['omg']
    multi = 'â—•_â—•'
  [multi.oneeighth]
    words = ['1/8']
    multi = 'â…›'
  [multi.onefourth]
    words = ['1/4']
    multi = 'Â¼'
  [multi.onehalf]
    words = ['1/2']
    multi = 'Â½'
  [multi.onethird]
    words = ['1/3']
    multi = 'â…“'
  [multi.option]
    words = ['opt', 'option']
    multi = 'âŒ¥'
  [multi.ohreally]
    words = ['orly']
    multi = '(ëˆˆ_ëˆˆ)'
  [multi.ohyou]
    words = ['ohyou', 'ou']
    multi = '(â—à°¥à±ªà°¥)á´–'
  [multi.peace]
    words = ['peace', 'victory']
    multi = 'âœŒ(-â€¿-)âœŒ'
  [multi.pear]
    words = ['pear']
    multi = '(__>-'
  [multi.pi]
    words = ['pi']
    multi = 'Ï€'
  [multi.pingpong]
    words = ['pingpong']
    multi = '( â€¢_â€¢)O*Â¯`Â·.Â¸.Â·Â´Â¯`Â°Q(â€¢_â€¢ )'
  [multi.plain]
    words = ['plain']
    multi = '._.'
  [multi.pleased]
    words = ['pleased']
    multi = '(Ë¶â€¾á·„ â»Ì« â€¾á·…Ëµ)'
  [multi.point]
    words = ['point']
    multi = '(â˜ï¾Ÿãƒ®ï¾Ÿ)â˜'
  [multi.pooh]
    words = ['pooh']
    multi = 'Ê• â€¢ÌØˆâ€¢Ì€)'
  [multi.pound]
    words = ['pound']
    multi = 'Â£'
  [multi.praise]
    words = ['praise']
    multi = '(â˜ Õà¨Š Õ)â˜'
  #[multi.punch]
  #  words = ['punch']
  #  multi = 'O=(\'-\'Q)'
  [multi.rage]
    words = ['rage', 'mad']
    multi = 't(à² ç›Šà² t)'
  [multi.rageflip]
    words = ['rageflip']
    multi = '(ãƒà² ç›Šà² )ãƒå½¡â”»â”â”»'
  [multi.rainbowcat]
    words = ['rainbowcat']
    multi = '(=^ï½¥ï½ªï½¥^=))ï¾‰å½¡â˜†'
  [multi.really]
    words = ['really']
    multi = 'Ã²_Ã´'
  [multi.registered]
    words = ['r']
    multi = 'Â®'
  [multi.right]
    words = ['right', '->']
    multi = 'â†’'
  [multi.riot]
    words = ['riot']
    multi = 'à­§à¼¼à² ç›Šà² à¼½à­¨'
  [multi.rolleyes]
    words = ['rolleyes']
    multi = '(â—”_â—”)'
  [multi.rose ]
    words = ['rose']
    multi = 'âœ¿Ú¿Ú°Û£â€”'
  [multi.run]
    words = ['run']
    multi = '(â•¯Â°â–¡Â°)â•¯'
  [multi.sad]
    words = ['sad']
    multi = 'Îµ(Â´ï­ï¸µï­`)Ğ·'
  [multi.saddonger]
    words = ['saddonger']
    multi = 'ãƒ½à¼¼àºˆÊ–Ì¯àºˆà¼½ï¾‰'
  [multi.sadlenny]
    words = ['sadlenny']
    multi = '( Í¡Â° Ê–Ì¯ Í¡Â°)'
  [multi.seveneigths]
    words = ['7/8']
    multi = 'â…'
  [multi.sharp]
    words = ['sharp', 'diesis']
    multi = 'â™¯'
  [multi.shout]
    words = ['shout']
    multi = 'â•š(â€¢âŒ‚â€¢)â•'
  [multi.shrug]
    words = ['shrug']
    multi = 'Â¯\_(ãƒ„)_/Â¯'
  [multi.shy]
    words = ['shy']
    multi = '=^_^='
  [multi.sigma]
    words = ['sigma', 'sum']
    multi = 'Î£'
  [multi.skull]
    words = ['skull']
    multi = 'â˜ '
  [multi.smile]
    words = ['smile']
    multi = 'ãƒ„'
  [multi.smiley]
    words = ['smiley']
    multi = 'â˜ºï¸'
  [multi.smirk]
    words = ['smirk']
    multi = 'Â¬â€¿Â¬'
  [multi.snowman]
    words = ['snowman']
    multi = 'â˜ƒ'
  [multi.sob]
    words = ['sob']
    multi = '(;Â´à¼àº¶Ğ”à¼àº¶`)'
  [multi.spade]
    words = ['spade']
    multi = 'â™ '
  [multi.squareroot]
    words = ['sqrt']
    multi = 'âˆš'
  [multi.squid]
    words = ['squid']
    multi = '<ã‚³:å½¡'
  [multi.star]
    words = ['star']
    multi = 'â˜…'
  [multi.strong]
    words = ['strong']
    multi = 'á•™(â‡€â€¸â†¼â€¶)á•—'
  [multi.suicide]
    words = ['suicide']
    multi = 'Îµ/ÌµÍ‡Ì¿Ì¿/â€™Ì¿â€™Ì¿ Ì¿(â—¡ï¸µâ—¡)'
  [multi.sum]
    words = ['sum']
    multi = 'âˆ‘'
  [multi.sun]
    words = ['sun']
    multi = 'â˜€'
  [multi.surprised]
    words = ['surprised']
    multi = '(à¹‘â€¢Ì ãƒ® â€¢Ì€à¹‘)'
  [multi.surrender]
    words = ['surrender']
    multi = '\\_(-_-)_/'
  [multi.stalker]
    words = ['stalker']
    multi = 'â”¬â”´â”¬â”´â”¤(ï½¥_â”œâ”¬â”´â”¬â”´'
  [multi.swag]
    words = ['swag']
    multi = '(Ì¿â–€Ì¿â€¿â€‰Ì¿â–€Ì¿ Ì¿)'
  [multi.sword]
    words = ['sword']
    multi = 'o()xxxx[{::::::::::::::::::>'
  [multi.tabledown]
    words = ['tabledown']
    multi = 'â”¬â”€â”¬ï»¿ ãƒ( ã‚œ-ã‚œãƒ)'
  [multi.tableflip]
    words = ['tableflip']
    multi = '(ãƒ ã‚œĞ”ã‚œ)ãƒ ï¸µ â”»â”â”»'
  [multi.tau]
    words = ['tau']
    multi = 'Ï„'
  [multi.tears]
    words = ['tears']
    multi = '(à²¥ï¹à²¥)'
  [multi.terrorist]
    words = ['terrorist']
    multi = 'à­§à¼¼à² ç›Šà² à¼½ï¸»â•¦â•¤â”€'
  [multi.thanks]
    words = ['thanks', 'thankyou', 'ty']
    multi = '\\(^-^)/'
  [multi.therefore]
    words = ['therefore', 'so']
    multi = 'â¸«'
  [multi.threeeights]
    words = ['3/8']
    multi = 'â…œ'
  [multi.tiefighter]
    words = ['tiefighter']
    multi = '|=-(Â¤)-=|'
  [multi.tired]
    words = ['tired']
    multi = '(=____=)'
  [multi.toldyouso]
    words = ['toldyouso', 'toldyou']
    multi = 'â˜œ(ê’¡âŒ“ê’¡)'
  [multi.toogood]
    words = ['toogood']
    multi = 'á•¦(Ã²á´¥Ã³)á•¥'
  [multi.trademark]
    words = ['tm']
    multi = 'â„¢'
  [multi.triangle]
    words = ['triangle', 't']
    multi = 'â–²'
  [multi.twothirds]
    words = ['2/3']
    multi = 'â…”'
  [multi.unflip]
    words = ['unflip']
    multi = 'â”¬â”€â”€â”¬ ãƒ(Ã²_Ã³ãƒ)'
  [multi.up]
    words = ['up']
    multi = 'â†‘'
  [multi.victory]
    words = ['victory']
    multi = '(à¹‘â€¢Ì€ã…‚â€¢Ì)à¸‡âœ§'
  [multi.wat]
    words = ['wat']
    multi = '(Ã’Ğ”Ã“×±)'
  [multi.wave]
    words = ['wave']
    multi = '( * ^ *) ãƒã‚·'
  [multi.whaa]
    words = ['whaa']
    multi = 'Ã–'
  [multi.whistle]
    words = ['whistle']
    multi = '(ã£^Ğ·^)â™ªâ™¬'
  [multi.whoa]
    words = ['whoa']
    multi = '(Â°oâ€¢)'
  [multi.why]
    words = ['why']
    multi = 'áƒš(`â—‰â—à±ªâ—Ÿâ—‰â€µáƒš)'
  [multi.woo]
    words = ['woo']
    multi = 'ï¼¼(ï¼¾Oï¼¾)ï¼'
  [multi.wtf]
    words = ['wtf']
    multi = '''(âŠ™ï¼¿âŠ™\')'''
  [multi.wut]
    words = ['wut']
    multi = 'âŠ™Ï‰âŠ™'
  [multi.yay]
    words = ['yay']
    multi = '\\( ï¾Ÿãƒ®ï¾Ÿ)/'
  [multi.yeah]
    words = ['yeah', 'yes']
    multi = '(â€¢Ì€á´—â€¢Ì)Ùˆ Ì‘Ì‘'
  [multi.yen]
    words = ['yen']
    multi = 'Â¥'
  [multi.yinyang]
    words = ['yinyang', 'yy']
    multi = 'â˜¯'
  [multi.yolo]
    words = ['yolo']
    multi = 'Yáµ’áµ˜ Oá¶°Ë¡Ê¸ Lá¶¤áµ›áµ‰ Oá¶°á¶œáµ‰'
  [multi.youkids]
    words = ['youkids', 'ukids']
    multi = 'áƒšà¼¼>â•­ ÍŸÊ–â•®<à¼½áƒš'
  [multi.yuno]
    words = ['y u no', 'yuno']
    multi = '(å±®ï¾ŸĞ”ï¾Ÿ)å±® Y U NO'
  [multi.zen]
    words = ['zen', 'meditation', 'omm']
    multi = 'âŠ¹â•°(âŒ£ÊŸâŒ£)â•¯âŠ¹'
  [multi.zoidberg]
    words = ['zoidberg']
    multi = '(V) (Â°,,,,Â°) (V)'
  [multi.zombie]
    words = ['zombie']
    multi = '[Â¬Âº-Â°]Â¬'
